### PR TITLE
Update wind bearing

### PR DESCRIPTION
**Pull request by ajtudela**
It seems that wind_bearing needs to be in degrees. 

With this change, the HA weather entity can retrieve that attribute and shows it in the frontend.

### CODE REVIEW

**Comment by outon** [comment]
I have reviewed the proposed change and the only difference is the language in which it indicates the direction of the wind. Currently the acronyms, which AEMET offer in Spanish,  N, S, E, O, NE, NO, SE, SO are converted to their corresponding values in English: N, S, E, W, NE, NW, SE, SW, ... son HA can work with them.

With the proposed change the value would remain in Spanish and not in English.

If what we want is to change it to degrees we would have to change the definition of the `WIND_DIRECTIONS` dictionary that is in `const.py`.

Changing the directions by their corresponding degrees
`WIND_DIRECTIONS = {"N": 0.0, "NNE": 22.5, "NE": 45.0, ...`

But we need to be sure that returning Wind Direction in Degrees is valid.

**Comment by ajtudela** [comment]
Hi, I don't know if something has changed in the AEMET data, but without the change, wind bearing can not be pushed into HA.

With the change:
Captura
Captura2

Without the change:
Captura3
Captura4

**Comment by outon** [comment]
I have found what was the problem.

On your first snapshot you can find wind bearing pointing to 122 degrees (near to ESE=112.5º). But in forecast section (in same snapshot) you can find wind bearing "E" (90º) at 16:00.

So, depending which weather station is the nearest to your location it may include wind speed and wind bearing (in degrees) or not include information at all.

In this last case, I retreive wind speed and bearing from hourly forecast which is informed with geographycal coordinates (N, S, E, W) instead of degrees.

I have corrected the code to include both cases.

**Comment by ajtudela** [comment]
I think is not the case. 
The weather station include the wind bearing:
Captura2

But it doesn't appear in HA:
Captura

But, I've updated the component and it works now. Thanks!!

**Pull request closed without merging**
